# Generated by Django 4.2.13 on 2025-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECFRNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='Path', max_length=512, verbose_name='Path')),
                ('identifier', models.CharField(db_index=True, help_text='Identifier', max_length=16, verbose_name='Identifier')),
                ('label', models.CharField(db_index=True, help_text='Label', max_length=128, verbose_name='Label')),
                ('label_level', models.CharField(db_index=True, help_text='Label Level', max_length=16, verbose_name='Label Level')),
                ('label_description', models.CharField(db_index=True, help_text='Label Description', max_length=128, verbose_name='Label Description')),
                ('label_type', models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('chapter', 'Chapter'), ('subchapter', 'Subchapter'), ('part', 'Part'), ('subpart', 'Subpart'), ('subject_group', 'Subject Group'), ('section', 'Section'), ('appendix', 'Appendix')], default='title', help_text='Label Type', max_length=16, verbose_name='Label Type')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('has_children', models.BooleanField(default=False, help_text='Has Children Nodes?', verbose_name='Has Children Nodes?')),
            ],
            options={
                'verbose_name': 'eCFR Node',
                'verbose_name_plural': 'eCFR Nodes',
                'ordering': ['id', 'path'],
            },
        ),
    ]
